name: golangci-lint
on: [push]
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - run: go version
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.53.3"
          args: --timeout=2m
  
